// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ToJSONRequest struct {
	Yaml                 string   `protobuf:"bytes,1,opt,name=yaml,proto3" json:"yaml,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToJSONRequest) Reset()         { *m = ToJSONRequest{} }
func (m *ToJSONRequest) String() string { return proto.CompactTextString(m) }
func (*ToJSONRequest) ProtoMessage()    {}
func (*ToJSONRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_493383cebe65e99a, []int{0}
}
func (m *ToJSONRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToJSONRequest.Unmarshal(m, b)
}
func (m *ToJSONRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToJSONRequest.Marshal(b, m, deterministic)
}
func (dst *ToJSONRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToJSONRequest.Merge(dst, src)
}
func (m *ToJSONRequest) XXX_Size() int {
	return xxx_messageInfo_ToJSONRequest.Size(m)
}
func (m *ToJSONRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ToJSONRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ToJSONRequest proto.InternalMessageInfo

func (m *ToJSONRequest) GetYaml() string {
	if m != nil {
		return m.Yaml
	}
	return ""
}

type ToJSONResponse struct {
	Json                 string   `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToJSONResponse) Reset()         { *m = ToJSONResponse{} }
func (m *ToJSONResponse) String() string { return proto.CompactTextString(m) }
func (*ToJSONResponse) ProtoMessage()    {}
func (*ToJSONResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_493383cebe65e99a, []int{1}
}
func (m *ToJSONResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToJSONResponse.Unmarshal(m, b)
}
func (m *ToJSONResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToJSONResponse.Marshal(b, m, deterministic)
}
func (dst *ToJSONResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToJSONResponse.Merge(dst, src)
}
func (m *ToJSONResponse) XXX_Size() int {
	return xxx_messageInfo_ToJSONResponse.Size(m)
}
func (m *ToJSONResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ToJSONResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ToJSONResponse proto.InternalMessageInfo

func (m *ToJSONResponse) GetJson() string {
	if m != nil {
		return m.Json
	}
	return ""
}

type ToJSONBytesRequest struct {
	Yaml                 []byte   `protobuf:"bytes,1,opt,name=yaml,proto3" json:"yaml,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToJSONBytesRequest) Reset()         { *m = ToJSONBytesRequest{} }
func (m *ToJSONBytesRequest) String() string { return proto.CompactTextString(m) }
func (*ToJSONBytesRequest) ProtoMessage()    {}
func (*ToJSONBytesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_493383cebe65e99a, []int{2}
}
func (m *ToJSONBytesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToJSONBytesRequest.Unmarshal(m, b)
}
func (m *ToJSONBytesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToJSONBytesRequest.Marshal(b, m, deterministic)
}
func (dst *ToJSONBytesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToJSONBytesRequest.Merge(dst, src)
}
func (m *ToJSONBytesRequest) XXX_Size() int {
	return xxx_messageInfo_ToJSONBytesRequest.Size(m)
}
func (m *ToJSONBytesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ToJSONBytesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ToJSONBytesRequest proto.InternalMessageInfo

func (m *ToJSONBytesRequest) GetYaml() []byte {
	if m != nil {
		return m.Yaml
	}
	return nil
}

type ToJSONBytesResponse struct {
	Json                 []byte   `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToJSONBytesResponse) Reset()         { *m = ToJSONBytesResponse{} }
func (m *ToJSONBytesResponse) String() string { return proto.CompactTextString(m) }
func (*ToJSONBytesResponse) ProtoMessage()    {}
func (*ToJSONBytesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_493383cebe65e99a, []int{3}
}
func (m *ToJSONBytesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToJSONBytesResponse.Unmarshal(m, b)
}
func (m *ToJSONBytesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToJSONBytesResponse.Marshal(b, m, deterministic)
}
func (dst *ToJSONBytesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToJSONBytesResponse.Merge(dst, src)
}
func (m *ToJSONBytesResponse) XXX_Size() int {
	return xxx_messageInfo_ToJSONBytesResponse.Size(m)
}
func (m *ToJSONBytesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ToJSONBytesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ToJSONBytesResponse proto.InternalMessageInfo

func (m *ToJSONBytesResponse) GetJson() []byte {
	if m != nil {
		return m.Json
	}
	return nil
}

func init() {
	proto.RegisterType((*ToJSONRequest)(nil), "dio.hellogrpcweb.v1.ToJSONRequest")
	proto.RegisterType((*ToJSONResponse)(nil), "dio.hellogrpcweb.v1.ToJSONResponse")
	proto.RegisterType((*ToJSONBytesRequest)(nil), "dio.hellogrpcweb.v1.ToJSONBytesRequest")
	proto.RegisterType((*ToJSONBytesResponse)(nil), "dio.hellogrpcweb.v1.ToJSONBytesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// YAMLServiceClient is the client API for YAMLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type YAMLServiceClient interface {
	ToJSON(ctx context.Context, in *ToJSONRequest, opts ...grpc.CallOption) (*ToJSONResponse, error)
	ToJSONBytes(ctx context.Context, in *ToJSONBytesRequest, opts ...grpc.CallOption) (*ToJSONBytesResponse, error)
}

type yAMLServiceClient struct {
	cc *grpc.ClientConn
}

func NewYAMLServiceClient(cc *grpc.ClientConn) YAMLServiceClient {
	return &yAMLServiceClient{cc}
}

func (c *yAMLServiceClient) ToJSON(ctx context.Context, in *ToJSONRequest, opts ...grpc.CallOption) (*ToJSONResponse, error) {
	out := new(ToJSONResponse)
	err := c.cc.Invoke(ctx, "/dio.hellogrpcweb.v1.YAMLService/ToJSON", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *yAMLServiceClient) ToJSONBytes(ctx context.Context, in *ToJSONBytesRequest, opts ...grpc.CallOption) (*ToJSONBytesResponse, error) {
	out := new(ToJSONBytesResponse)
	err := c.cc.Invoke(ctx, "/dio.hellogrpcweb.v1.YAMLService/ToJSONBytes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YAMLServiceServer is the server API for YAMLService service.
type YAMLServiceServer interface {
	ToJSON(context.Context, *ToJSONRequest) (*ToJSONResponse, error)
	ToJSONBytes(context.Context, *ToJSONBytesRequest) (*ToJSONBytesResponse, error)
}

func RegisterYAMLServiceServer(s *grpc.Server, srv YAMLServiceServer) {
	s.RegisterService(&_YAMLService_serviceDesc, srv)
}

func _YAMLService_ToJSON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToJSONRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YAMLServiceServer).ToJSON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dio.hellogrpcweb.v1.YAMLService/ToJSON",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YAMLServiceServer).ToJSON(ctx, req.(*ToJSONRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _YAMLService_ToJSONBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToJSONBytesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YAMLServiceServer).ToJSONBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dio.hellogrpcweb.v1.YAMLService/ToJSONBytes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YAMLServiceServer).ToJSONBytes(ctx, req.(*ToJSONBytesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _YAMLService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dio.hellogrpcweb.v1.YAMLService",
	HandlerType: (*YAMLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ToJSON",
			Handler:    _YAMLService_ToJSON_Handler,
		},
		{
			MethodName: "ToJSONBytes",
			Handler:    _YAMLService_ToJSONBytes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor_hello_493383cebe65e99a) }

var fileDescriptor_hello_493383cebe65e99a = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x4e, 0xc9, 0xcc, 0xd7, 0x03, 0x0b, 0xa4,
	0x17, 0x15, 0x24, 0x97, 0xa7, 0x26, 0xe9, 0x95, 0x19, 0x4a, 0xc9, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7,
	0xa4, 0xea, 0x27, 0x16, 0x64, 0xea, 0x27, 0xe6, 0xe5, 0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7,
	0x15, 0x43, 0xb4, 0x28, 0x29, 0x73, 0xf1, 0x86, 0xe4, 0x7b, 0x05, 0xfb, 0xfb, 0x05, 0xa5, 0x16,
	0x96, 0xa6, 0x16, 0x97, 0x08, 0x09, 0x71, 0xb1, 0x54, 0x26, 0xe6, 0xe6, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0x70, 0x06, 0x81, 0xd9, 0x4a, 0x2a, 0x5c, 0x7c, 0x30, 0x45, 0xc5, 0x05, 0xf9, 0x79, 0xc5,
	0xa9, 0x20, 0x55, 0x59, 0xc5, 0xf9, 0x79, 0x30, 0x55, 0x20, 0xb6, 0x92, 0x06, 0x97, 0x10, 0x44,
	0x95, 0x53, 0x65, 0x49, 0x6a, 0x31, 0x36, 0xf3, 0x78, 0xa0, 0xe6, 0x69, 0x72, 0x09, 0xa3, 0xa8,
	0xc4, 0x62, 0x28, 0x0f, 0xc4, 0x50, 0xa3, 0x47, 0x8c, 0x5c, 0xdc, 0x91, 0x8e, 0xbe, 0x3e, 0xc1,
	0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x89, 0x5c, 0x6c, 0x10, 0xad, 0x42, 0x4a, 0x7a, 0x58,
	0x7c, 0xab, 0x87, 0xe2, 0x19, 0x29, 0x65, 0xbc, 0x6a, 0x20, 0xd6, 0x2a, 0xf1, 0x35, 0x5d, 0x7e,
	0x32, 0x99, 0x89, 0x43, 0x89, 0x59, 0xbf, 0xcc, 0xd0, 0x8a, 0x51, 0x4b, 0xa8, 0x80, 0x8b, 0x1b,
	0xc9, 0x75, 0x42, 0xea, 0x78, 0xcc, 0x40, 0xf6, 0xa9, 0x94, 0x06, 0x61, 0x85, 0xd8, 0x6d, 0x74,
	0x62, 0x89, 0x62, 0x2a, 0x33, 0x4c, 0x62, 0x03, 0xc7, 0x88, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x53, 0xeb, 0xfd, 0xe2, 0xd3, 0x01, 0x00, 0x00,
}
