/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('./google/api/annotations_pb.js');
goog.exportSymbol('proto.dio.hellogrpcweb.v1.ToJSONBytesRequest', null, global);
goog.exportSymbol('proto.dio.hellogrpcweb.v1.ToJSONBytesResponse', null, global);
goog.exportSymbol('proto.dio.hellogrpcweb.v1.ToJSONRequest', null, global);
goog.exportSymbol('proto.dio.hellogrpcweb.v1.ToJSONResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dio.hellogrpcweb.v1.ToJSONRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dio.hellogrpcweb.v1.ToJSONRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dio.hellogrpcweb.v1.ToJSONRequest.displayName = 'proto.dio.hellogrpcweb.v1.ToJSONRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dio.hellogrpcweb.v1.ToJSONRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.dio.hellogrpcweb.v1.ToJSONRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dio.hellogrpcweb.v1.ToJSONRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dio.hellogrpcweb.v1.ToJSONRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    yaml: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dio.hellogrpcweb.v1.ToJSONRequest}
 */
proto.dio.hellogrpcweb.v1.ToJSONRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dio.hellogrpcweb.v1.ToJSONRequest;
  return proto.dio.hellogrpcweb.v1.ToJSONRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dio.hellogrpcweb.v1.ToJSONRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dio.hellogrpcweb.v1.ToJSONRequest}
 */
proto.dio.hellogrpcweb.v1.ToJSONRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setYaml(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dio.hellogrpcweb.v1.ToJSONRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dio.hellogrpcweb.v1.ToJSONRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dio.hellogrpcweb.v1.ToJSONRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dio.hellogrpcweb.v1.ToJSONRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getYaml();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string yaml = 1;
 * @return {string}
 */
proto.dio.hellogrpcweb.v1.ToJSONRequest.prototype.getYaml = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.dio.hellogrpcweb.v1.ToJSONRequest.prototype.setYaml = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dio.hellogrpcweb.v1.ToJSONResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dio.hellogrpcweb.v1.ToJSONResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dio.hellogrpcweb.v1.ToJSONResponse.displayName = 'proto.dio.hellogrpcweb.v1.ToJSONResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dio.hellogrpcweb.v1.ToJSONResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.dio.hellogrpcweb.v1.ToJSONResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dio.hellogrpcweb.v1.ToJSONResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dio.hellogrpcweb.v1.ToJSONResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    json: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dio.hellogrpcweb.v1.ToJSONResponse}
 */
proto.dio.hellogrpcweb.v1.ToJSONResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dio.hellogrpcweb.v1.ToJSONResponse;
  return proto.dio.hellogrpcweb.v1.ToJSONResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dio.hellogrpcweb.v1.ToJSONResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dio.hellogrpcweb.v1.ToJSONResponse}
 */
proto.dio.hellogrpcweb.v1.ToJSONResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setJson(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dio.hellogrpcweb.v1.ToJSONResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dio.hellogrpcweb.v1.ToJSONResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dio.hellogrpcweb.v1.ToJSONResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dio.hellogrpcweb.v1.ToJSONResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJson();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string json = 1;
 * @return {string}
 */
proto.dio.hellogrpcweb.v1.ToJSONResponse.prototype.getJson = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.dio.hellogrpcweb.v1.ToJSONResponse.prototype.setJson = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dio.hellogrpcweb.v1.ToJSONBytesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dio.hellogrpcweb.v1.ToJSONBytesRequest.displayName = 'proto.dio.hellogrpcweb.v1.ToJSONBytesRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.dio.hellogrpcweb.v1.ToJSONBytesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dio.hellogrpcweb.v1.ToJSONBytesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    yaml: msg.getYaml_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dio.hellogrpcweb.v1.ToJSONBytesRequest}
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dio.hellogrpcweb.v1.ToJSONBytesRequest;
  return proto.dio.hellogrpcweb.v1.ToJSONBytesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dio.hellogrpcweb.v1.ToJSONBytesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dio.hellogrpcweb.v1.ToJSONBytesRequest}
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setYaml(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dio.hellogrpcweb.v1.ToJSONBytesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dio.hellogrpcweb.v1.ToJSONBytesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getYaml_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes yaml = 1;
 * @return {!(string|Uint8Array)}
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesRequest.prototype.getYaml = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes yaml = 1;
 * This is a type-conversion wrapper around `getYaml()`
 * @return {string}
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesRequest.prototype.getYaml_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getYaml()));
};


/**
 * optional bytes yaml = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getYaml()`
 * @return {!Uint8Array}
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesRequest.prototype.getYaml_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getYaml()));
};


/** @param {!(string|Uint8Array)} value */
proto.dio.hellogrpcweb.v1.ToJSONBytesRequest.prototype.setYaml = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.dio.hellogrpcweb.v1.ToJSONBytesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.dio.hellogrpcweb.v1.ToJSONBytesResponse.displayName = 'proto.dio.hellogrpcweb.v1.ToJSONBytesResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.dio.hellogrpcweb.v1.ToJSONBytesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.dio.hellogrpcweb.v1.ToJSONBytesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    json: msg.getJson_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.dio.hellogrpcweb.v1.ToJSONBytesResponse}
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.dio.hellogrpcweb.v1.ToJSONBytesResponse;
  return proto.dio.hellogrpcweb.v1.ToJSONBytesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.dio.hellogrpcweb.v1.ToJSONBytesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.dio.hellogrpcweb.v1.ToJSONBytesResponse}
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setJson(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.dio.hellogrpcweb.v1.ToJSONBytesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.dio.hellogrpcweb.v1.ToJSONBytesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getJson_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes json = 1;
 * @return {!(string|Uint8Array)}
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesResponse.prototype.getJson = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes json = 1;
 * This is a type-conversion wrapper around `getJson()`
 * @return {string}
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesResponse.prototype.getJson_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getJson()));
};


/**
 * optional bytes json = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getJson()`
 * @return {!Uint8Array}
 */
proto.dio.hellogrpcweb.v1.ToJSONBytesResponse.prototype.getJson_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getJson()));
};


/** @param {!(string|Uint8Array)} value */
proto.dio.hellogrpcweb.v1.ToJSONBytesResponse.prototype.setJson = function(value) {
  jspb.Message.setProto3BytesField(this, 1, value);
};


goog.object.extend(exports, proto.dio.hellogrpcweb.v1);
